[package]
name = "steno-lookup"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]
edition = "2018"

[dependencies]
directories = "1.0"
rayon = "1.0"
rust-ini = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
